name = "JellyMe4"
uuid = "19ac8677-9a15-4623-9afd-84acc6165ce7"
authors = ["Phillip Alday <me@phillipalday.com>"]
version = "1.2.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
RegressionFormulae = "545c379f-4ec2-4339-9aea-38f2fb6a8ba2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Aqua = "0.7"
CategoricalArrays = "0.8, 0.9, 0.10"
DataFrames = "1"
Distributions = "0.25"
GLM = "1.3"
LinearAlgebra = "0, 1"
MixedModels = "4"
RCall = "0.13, 0.14"
RegressionFormulae = "0.1"
StatsBase = "0.31, 0.32, 0.33, 0.34"
StatsModels = "0.6, 0.7"
Tables = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
